name: check-codebase

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install a Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test --verbose
